site_name: Birdwatch
site_description: A command-line tool for logging bird sightings
repo_url: https://github.com/mtnlark/birdwatch
repo_name: mtnlark/birdwatch

nav:
  - Home: index.md
  - Usage: usage.md
  - Reference: reference.md
  - Contributing: contributing.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - content.code.annotate
    - toc.integrate
    - search.suggest
    - search.highlight
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  font:
    text: Inter
    code: Fira Code
  icon:
    repo: fontawesome/brands/github
    logo: material/bird

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - tables
  - def_list
  - footnotes

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mtnlark/birdwatch

plugins:
  - search
  - tags



